//! The typed Job-template patch: a pure overlay of per-run fields onto a Job
//! spec fetched from a ConfigMap. Everything here is fail-loud — a patch that
//! silently matches nothing (a renamed container, a missing env array) is how a
//! Job ends up running the template's default image with none of the run's env,
//! producing a confidently wrong verdict. Every target that cannot be found is
//! an error, never a no-op.

use serde_json::Value;

/// A per-run overlay onto a Job template. Deliberately small: only the fields
/// that vary run-to-run. Anything structural (SA, volumes, sidecars, limits)
/// stays in the template.
#[derive(Debug, Clone, Default)]
pub struct JobPatch {
    /// `metadata.name` for the Job.
    pub job_name: String,
    /// Labels merged into BOTH `metadata.labels` and the pod template's
    /// `spec.template.metadata.labels` (so selectors and the Job match).
    pub labels: Vec<(String, String)>,
    /// Per-container image overrides: `(container_name, image)`. A named
    /// container that is absent is an error.
    pub images: Vec<(String, String)>,
    /// Per-container env upserts. The executor computes these — the runner's own
    /// env AND the candidate's binding (which env var maps to which artifact,
    /// read from the env profile) — so this type carries no candidate-specific
    /// names and stays generic.
    pub env: Vec<EnvUpsert>,
    /// Optional `metadata.ownerReferences` entry. Makes the Job a child of a
    /// stable, same-namespace owner (the chart-managed template ConfigMap) so it
    /// shows in ArgoCD's resource tree and is cascade-GC'd. `None` leaves the Job
    /// un-owned (the pre-ownerRef behavior).
    pub owner: Option<OwnerRef>,
    /// Optional per-run repoint of the config-file volume at a specific record
    /// version's ConfigMap. `None` leaves the template's default in place.
    pub config_artifacts: Option<ConfigArtifacts>,
    /// Optional L1 config env COPIED from the recorded system's rendered workload.
    /// Replaces the candidate's `env`/`envFrom` wholesale before the per-run env
    /// upserts (which therefore win, as the replay overrides must).
    pub config_env: Option<ConfigEnvCopy>,
}

/// Repoint the config-file volume at one record version's ConfigMap (the config
/// baseline the candidate reads from disk — the part that is a FILE, not env).
/// Both names are supplied by the caller from deployment profile data, so no
/// recorded system's vocabulary appears here. The volume must exist in the
/// template: a missing one is a loud error, never a silent boot against another
/// version's config (a wrong-verdict trap).
#[derive(Debug, Clone)]
pub struct ConfigArtifacts {
    /// The Job template's volume to repoint.
    pub volume: String,
    /// ConfigMap it should mount for this run.
    pub config_map: String,
}

/// The recorded system's own generated container env, copied verbatim.
///
/// This is the whole point of the design: the env is GENERATED by the recorded
/// system's chart (from its own config values, at its own version) and copied
/// as-is — including every `valueFrom.secretKeyRef` indirection, under whatever
/// names that system declares. Nothing is enumerated, remapped, or resolved here,
/// so a config key or secret added to that system tomorrow needs no change in this
/// codebase, and no secret VALUE is ever read by the orchestrator.
#[derive(Debug, Clone)]
pub struct ConfigEnvCopy {
    /// Candidate container that receives the copied env.
    pub container: String,
    /// The source container's `env` list, verbatim.
    pub env: Vec<Value>,
    /// The source container's `envFrom` list, verbatim.
    pub env_from: Vec<Value>,
}

/// A single Kubernetes ownerReference. The owner MUST be same-namespace as the
/// Job (k8s forbids cross-namespace ownerRefs — a cross-ns ref makes the Job
/// create fail). `controller` and `blockOwnerDeletion` are always false here: the
/// owner exists only to give the Job a resource-tree parent (visibility) and
/// cascade GC, never to control the Job's lifecycle or wedge the owner's own
/// deletion on a still-running Job.
#[derive(Debug, Clone)]
pub struct OwnerRef {
    pub api_version: String,
    pub kind: String,
    pub name: String,
    pub uid: String,
}

/// Upsert one env var on one container: replace the entry with this `name` if
/// present, else append it. Keyed by `(container, name)`.
#[derive(Debug, Clone)]
pub struct EnvUpsert {
    pub container: String,
    pub name: String,
    pub value: String,
}

impl EnvUpsert {
    pub fn new(
        container: impl Into<String>,
        name: impl Into<String>,
        value: impl Into<String>,
    ) -> Self {
        Self {
            container: container.into(),
            name: name.into(),
            value: value.into(),
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum PatchError {
    /// The template is not shaped like a Job (missing the path we must patch).
    Shape(String),
    /// A patch names a container the template does not define.
    ContainerNotFound { container: String },
}

impl std::fmt::Display for PatchError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PatchError::Shape(p) => write!(f, "job template not shaped as expected: {p}"),
            PatchError::ContainerNotFound { container } => write!(
                f,
                "patch targets container '{container}' but the template defines no such container"
            ),
        }
    }
}

impl std::error::Error for PatchError {}

/// Apply the patch, returning a new Job value. The input template is not
/// mutated. Fails loudly if any target is absent.
pub fn apply_job_patch(template: &Value, patch: &JobPatch) -> Result<Value, PatchError> {
    let mut job = template.clone();

    // metadata.name
    let metadata = job
        .get_mut("metadata")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| PatchError::Shape("metadata".into()))?;
    metadata.insert("name".into(), Value::String(patch.job_name.clone()));

    // metadata.labels (create the map if absent)
    merge_labels(
        metadata
            .entry("labels")
            .or_insert_with(|| Value::Object(Default::default())),
        &patch.labels,
    )?;

    // metadata.ownerReferences (optional). Stamp a single owner so the Job shows
    // in the owner's resource tree (ArgoCD renders it as a child of the chart-
    // managed template ConfigMap) and is cascade-GC'd. controller=false +
    // blockOwnerDeletion=false: tree/GC only, never lifecycle control.
    if let Some(owner) = &patch.owner {
        metadata.insert(
            "ownerReferences".into(),
            serde_json::json!([{
                "apiVersion": owner.api_version,
                "kind": owner.kind,
                "name": owner.name,
                "uid": owner.uid,
                "controller": false,
                "blockOwnerDeletion": false,
            }]),
        );
    }

    // spec.template.metadata.labels — the pod labels the Job's selector matches.
    {
        let pod_meta = job
            .pointer_mut("/spec/template/metadata")
            .ok_or_else(|| PatchError::Shape("spec.template.metadata".into()))?;
        let pod_meta = pod_meta
            .as_object_mut()
            .ok_or_else(|| PatchError::Shape("spec.template.metadata".into()))?;
        merge_labels(
            pod_meta
                .entry("labels")
                .or_insert_with(|| Value::Object(Default::default())),
            &patch.labels,
        )?;
    }

    // Config artifacts: repoint the config-file volume at this run's record
    // version. Applied before the images/env early-return so a config-only patch
    // still lands.
    if let Some(ca) = &patch.config_artifacts {
        apply_config_artifacts(&mut job, ca)?;
    }

    // L1: the recorded system's generated env, copied wholesale. Applied BEFORE
    // the per-run upserts below so the replay overrides (localhost stores, replay
    // mode, run id) win over the recorded values they must displace.
    if let Some(ce) = &patch.config_env {
        let c = find_container_in_job(&mut job, &ce.container)?;
        c.insert("env".into(), Value::Array(ce.env.clone()));
        c.insert("envFrom".into(), Value::Array(ce.env_from.clone()));
    }

    // Image + env target a named container, which may be a main container OR an
    // initContainer (e.g. the `migrations` init that pulls the CodeBundle by
    // sha). Both arrays are searched; a name in neither is a loud error.
    if patch.images.is_empty() && patch.env.is_empty() {
        return Ok(job);
    }

    for (name, image) in &patch.images {
        let c = find_container_in_job(&mut job, name)?;
        c.insert("image".into(), Value::String(image.clone()));
    }

    for up in &patch.env {
        let c = find_container_in_job(&mut job, &up.container)?;
        let env = c
            .entry("env")
            .or_insert_with(|| Value::Array(Vec::new()))
            .as_array_mut()
            .ok_or_else(|| {
                PatchError::Shape(format!("container '{}' env is not a list", up.container))
            })?;
        upsert_env(env, &up.name, &up.value);
    }

    Ok(job)
}

fn merge_labels(target: &mut Value, labels: &[(String, String)]) -> Result<(), PatchError> {
    let map = target
        .as_object_mut()
        .ok_or_else(|| PatchError::Shape("labels is not a map".into()))?;
    for (k, v) in labels {
        map.insert(k.clone(), Value::String(v.clone()));
    }
    Ok(())
}

/// Repoint the pod's config-file volume at a specific record version's ConfigMap.
/// The volume and its configMap must exist — silently keeping the template default
/// would boot the candidate against another version's config baseline and produce a
/// confidently wrong verdict, so both are loud errors.
fn apply_config_artifacts(job: &mut Value, ca: &ConfigArtifacts) -> Result<(), PatchError> {
    let vols = job
        .pointer_mut("/spec/template/spec/volumes")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| PatchError::Shape("spec.template.spec.volumes".into()))?;
    let vol = vols
        .iter_mut()
        .find(|v| v.get("name").and_then(Value::as_str) == Some(ca.volume.as_str()))
        .ok_or_else(|| PatchError::Shape(format!("volume '{}' not found", ca.volume)))?;
    let cm = vol
        .get_mut("configMap")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| PatchError::Shape(format!("volume '{}' has no configMap", ca.volume)))?;
    cm.insert("name".into(), Value::String(ca.config_map.clone()));
    Ok(())
}

/// Every distinct secret named by a `valueFrom.secretKeyRef` in a copied env list.
/// The launcher checks each exists BEFORE creating the Job, so a missing secret is
/// a named refusal instead of an opaque container-create failure at pod start.
/// Discovered from the data — this code never knows any secret's name.
pub fn referenced_secret_names(env: &[Value]) -> Vec<String> {
    let mut names: Vec<String> = env
        .iter()
        .filter_map(|e| {
            e.pointer("/valueFrom/secretKeyRef/name")
                .and_then(Value::as_str)
                .map(str::to_owned)
        })
        .collect();
    names.sort();
    names.dedup();
    names
}

/// Find a container by name across BOTH the pod's `containers` and its
/// `initContainers`, returning a mutable handle. initContainers are included so
/// a per-run patch can reach e.g. the migrations init that pulls the CodeBundle.
/// Two-step (locate the array immutably, then fetch mutably) to satisfy the
/// borrow checker without cloning.
fn find_container_in_job<'a>(
    job: &'a mut Value,
    name: &str,
) -> Result<&'a mut serde_json::Map<String, Value>, PatchError> {
    const ARRAYS: [&str; 2] = [
        "/spec/template/spec/containers",
        "/spec/template/spec/initContainers",
    ];
    let mut target: Option<&'static str> = None;
    for path in ARRAYS {
        let here = job
            .pointer(path)
            .and_then(Value::as_array)
            .map(|arr| {
                arr.iter()
                    .any(|c| c.get("name").and_then(Value::as_str) == Some(name))
            })
            .unwrap_or(false);
        if here {
            target = Some(path);
            break;
        }
    }
    let path = target.ok_or_else(|| PatchError::ContainerNotFound {
        container: name.to_owned(),
    })?;
    job.pointer_mut(path)
        .and_then(Value::as_array_mut)
        .and_then(|arr| {
            arr.iter_mut()
                .find(|c| c.get("name").and_then(Value::as_str) == Some(name))
        })
        .and_then(Value::as_object_mut)
        .ok_or_else(|| PatchError::ContainerNotFound {
            container: name.to_owned(),
        })
}

/// Replace the `{name,value}` entry with this name, or append it. k8s env is an
/// ordered list of `{name, value}`; a duplicate name is undefined, so upsert.
fn upsert_env(env: &mut Vec<Value>, name: &str, value: &str) {
    let entry = serde_json::json!({ "name": name, "value": value });
    if let Some(existing) = env
        .iter_mut()
        .find(|e| e.get("name").and_then(Value::as_str) == Some(name))
    {
        *existing = entry;
    } else {
        env.push(entry);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn template() -> Value {
        json!({
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": { "labels": { "app": "replay" } },
            "spec": {
                "template": {
                    "metadata": { "labels": { "app": "replay" } },
                    "spec": {
                        "containers": [
                            { "name": "runner", "image": "deja-orchestrator:template",
                              "env": [ { "name": "DEJA_RUN_ID", "value": "PLACEHOLDER" } ] },
                            { "name": "candidate", "image": "candidate:template" }
                        ]
                    }
                }
            }
        })
    }

    /// A template shaped like the replay-env Job: a `router-config` volume backed
    /// by a configMap, and a `candidate` container whose `envFrom` carries both a
    /// configMapRef (the ROUTER__* env) and a secretRef (replay-crypto).
    fn template_with_config_artifacts() -> Value {
        json!({
            "apiVersion": "batch/v1",
            "kind": "Job",
            "metadata": { "labels": {} },
            "spec": { "template": { "metadata": { "labels": {} }, "spec": {
                "volumes": [
                    { "name": "workspace", "emptyDir": {} },
                    { "name": "router-config",
                      "configMap": { "name": "router-cm-replay-default", "defaultMode": 420 } }
                ],
                "containers": [
                    { "name": "candidate", "image": "candidate:template",
                      "envFrom": [
                          { "configMapRef": { "name": "replay-default-hyperswitch-configs" } },
                          { "secretRef": { "name": "replay-crypto" } }
                      ] }
                ]
            }}}
        })
    }

    #[test]
    fn config_artifacts_repoints_volume_and_envfrom() {
        let patch = JobPatch {
            config_artifacts: Some(ConfigArtifacts {
                volume: "router-config".into(),
                config_map: "router-cm-replay-abc123".into(),
            }),
            ..Default::default()
        };
        let out = apply_job_patch(&template_with_config_artifacts(), &patch).expect("applies");
        let vols = out["spec"]["template"]["spec"]["volumes"]
            .as_array()
            .expect("volumes");
        let rc = vols
            .iter()
            .find(|v| v["name"] == json!("router-config"))
            .expect("router-config volume");
        assert_eq!(rc["configMap"]["name"], json!("router-cm-replay-abc123"));
        // defaultMode (structural) is preserved — only the name is repointed.
        assert_eq!(rc["configMap"]["defaultMode"], json!(420));
    }

    #[test]
    fn config_artifacts_missing_volume_is_loud() {
        // template() has no volumes at all — a repoint must error, not no-op.
        let patch = JobPatch {
            config_artifacts: Some(ConfigArtifacts {
                volume: "router-config".into(),
                config_map: "x".into(),
            }),
            ..Default::default()
        };
        let err = apply_job_patch(&template(), &patch).expect_err("no volumes -> error");
        assert!(matches!(err, PatchError::Shape(_)));
    }

    /// The copied env lands verbatim — including `secretKeyRef` indirection under
    /// the recorded system's OWN names — and the per-run replay overrides win over
    /// the recorded values they must displace.
    #[test]
    fn config_env_copy_lands_verbatim_and_run_env_wins() {
        let copied_env = vec![
            json!({ "name": "RUN_ENV", "value": "sandbox" }),
            json!({ "name": "ROUTER__MASTER_DATABASE__HOST", "value": "sbx-pg.internal" }),
            json!({ "name": "ROUTER__NETWORK_TOKENIZATION_SERVICE__PUBLIC_KEY",
                    "valueFrom": { "secretKeyRef": {
                        "name": "some-system-secrets", "key": "…__PUBLIC_KEY_NEW" } } }),
        ];
        let patch = JobPatch {
            config_env: Some(ConfigEnvCopy {
                container: "candidate".into(),
                env: copied_env,
                env_from: vec![json!({ "configMapRef": { "name": "recorded-configs" } })],
            }),
            // L2 replay override for a key the recorded env also sets.
            env: vec![EnvUpsert::new(
                "candidate",
                "ROUTER__MASTER_DATABASE__HOST",
                "127.0.0.1",
            )],
            ..Default::default()
        };
        let out = apply_job_patch(&template_with_config_artifacts(), &patch).expect("applies");
        let cand = &out["spec"]["template"]["spec"]["containers"][0];
        let env = cand["env"].as_array().expect("env");

        // secretKeyRef indirection preserved verbatim — name AND key, untouched.
        let pk = env
            .iter()
            .find(|e| e["name"] == json!("ROUTER__NETWORK_TOKENIZATION_SERVICE__PUBLIC_KEY"))
            .expect("copied secret ref");
        assert_eq!(
            pk["valueFrom"]["secretKeyRef"]["name"],
            json!("some-system-secrets")
        );
        assert_eq!(
            pk["valueFrom"]["secretKeyRef"]["key"],
            json!("…__PUBLIC_KEY_NEW")
        );
        // a plain recorded value survives
        assert_eq!(
            env.iter()
                .find(|e| e["name"] == json!("RUN_ENV"))
                .expect("copied RUN_ENV")["value"],
            json!("sandbox")
        );
        // the replay override REPLACED the recorded value (exactly once)
        let hosts: Vec<_> = env
            .iter()
            .filter(|e| e["name"] == json!("ROUTER__MASTER_DATABASE__HOST"))
            .collect();
        assert_eq!(hosts.len(), 1, "override replaces, not duplicates");
        assert_eq!(hosts[0]["value"], json!("127.0.0.1"));
        // envFrom came from the copy, replacing the template's own
        assert_eq!(
            cand["envFrom"][0]["configMapRef"]["name"],
            json!("recorded-configs")
        );
    }

    #[test]
    fn referenced_secret_names_are_discovered_deduped_from_data() {
        let env = vec![
            json!({ "name": "A", "valueFrom": { "secretKeyRef": { "name": "s1", "key": "k" } } }),
            json!({ "name": "B", "valueFrom": { "secretKeyRef": { "name": "s2", "key": "k" } } }),
            json!({ "name": "C", "valueFrom": { "secretKeyRef": { "name": "s1", "key": "j" } } }),
            // non-secret sources are ignored
            json!({ "name": "D", "valueFrom": { "fieldRef": { "fieldPath": "metadata.name" } } }),
            json!({ "name": "E", "value": "plain" }),
        ];
        assert_eq!(referenced_secret_names(&env), vec!["s1", "s2"]);
    }

    #[test]
    fn patches_name_labels_image_and_upserts_env() {
        let patch = JobPatch {
            job_name: "deja-replay-run7".into(),
            labels: vec![("deja.run-id".into(), "run7".into())],
            images: vec![("candidate".into(), "candidate:sha_c".into())],
            env: vec![
                // upsert existing
                EnvUpsert::new("runner", "DEJA_RUN_ID", "run7"),
                // append new
                EnvUpsert::new("runner", "RUNNER_EXPECTED_MIGRATIONS", "0001\n0002"),
                // env on a container that had none
                EnvUpsert::new("candidate", "ROUTER__DEJA__MODE", "replay"),
            ],
            ..Default::default()
        };
        let out = apply_job_patch(&template(), &patch).expect("patch applies");

        assert_eq!(out["metadata"]["name"], json!("deja-replay-run7"));
        assert_eq!(out["metadata"]["labels"]["deja.run-id"], json!("run7"));
        // pre-existing label preserved
        assert_eq!(out["metadata"]["labels"]["app"], json!("replay"));
        // pod template labels also carry the run id (selector match)
        assert_eq!(
            out["spec"]["template"]["metadata"]["labels"]["deja.run-id"],
            json!("run7")
        );

        let containers = out["spec"]["template"]["spec"]["containers"]
            .as_array()
            .expect("containers array");
        let runner = &containers[0];
        let candidate = &containers[1];
        assert_eq!(candidate["image"], json!("candidate:sha_c"));

        // DEJA_RUN_ID replaced in place, not duplicated.
        let runner_env = runner["env"].as_array().expect("runner env array");
        let run_ids: Vec<_> = runner_env
            .iter()
            .filter(|e| e["name"] == json!("DEJA_RUN_ID"))
            .collect();
        assert_eq!(run_ids.len(), 1, "no duplicate env name");
        assert_eq!(run_ids[0]["value"], json!("run7"));
        // new env appended
        assert!(runner_env
            .iter()
            .any(|e| e["name"] == json!("RUNNER_EXPECTED_MIGRATIONS")
                && e["value"] == json!("0001\n0002")));
        // candidate got a fresh env list
        assert_eq!(candidate["env"][0]["name"], json!("ROUTER__DEJA__MODE"));
        // no owner supplied -> no ownerReferences (default behavior)
        assert!(out["metadata"].get("ownerReferences").is_none());
    }

    #[test]
    fn stamps_owner_reference_when_owner_present() {
        let patch = JobPatch {
            job_name: "j".into(),
            owner: Some(OwnerRef {
                api_version: "v1".into(),
                kind: "ConfigMap".into(),
                name: "job-template".into(),
                uid: "cm-uid-123".into(),
            }),
            ..Default::default()
        };
        let out = apply_job_patch(&template(), &patch).expect("patch applies");
        let owners = out["metadata"]["ownerReferences"]
            .as_array()
            .expect("ownerReferences array");
        assert_eq!(owners.len(), 1, "exactly one owner");
        assert_eq!(owners[0]["apiVersion"], json!("v1"));
        assert_eq!(owners[0]["kind"], json!("ConfigMap"));
        assert_eq!(owners[0]["name"], json!("job-template"));
        assert_eq!(owners[0]["uid"], json!("cm-uid-123"));
        // tree/GC only — never controls the Job's lifecycle or wedges owner deletion
        assert_eq!(owners[0]["controller"], json!(false));
        assert_eq!(owners[0]["blockOwnerDeletion"], json!(false));
    }

    #[test]
    fn env_can_target_an_init_container() {
        // The CodeBundle URI must reach the `migrations` initContainer (Option B),
        // not a main container.
        let mut tmpl = template();
        tmpl["spec"]["template"]["spec"]["initContainers"] =
            json!([{ "name": "migrations", "image": "runner:tmpl" }]);
        let patch = JobPatch {
            job_name: "j".into(),
            env: vec![EnvUpsert::new(
                "migrations",
                "DEJA_CODE_BUNDLE_URI",
                "s3://art/codebundles/ff191d7f/migrations.tar",
            )],
            ..Default::default()
        };
        let out = apply_job_patch(&tmpl, &patch).expect("patch applies to init container");
        let inits = out["spec"]["template"]["spec"]["initContainers"]
            .as_array()
            .expect("initContainers array");
        assert_eq!(inits[0]["env"][0]["name"], json!("DEJA_CODE_BUNDLE_URI"));
        assert_eq!(
            inits[0]["env"][0]["value"],
            json!("s3://art/codebundles/ff191d7f/migrations.tar")
        );
    }

    #[test]
    fn missing_container_is_a_loud_error_not_a_noop() {
        let patch = JobPatch {
            job_name: "j".into(),
            images: vec![("router".into(), "x:y".into())], // template calls it "candidate"
            ..Default::default()
        };
        let err = apply_job_patch(&template(), &patch).expect_err("must reject missing container");
        assert_eq!(
            err,
            PatchError::ContainerNotFound {
                container: "router".into()
            }
        );
    }

    #[test]
    fn env_on_missing_container_is_also_loud() {
        let patch = JobPatch {
            job_name: "j".into(),
            env: vec![EnvUpsert::new("nope", "K", "V")],
            ..Default::default()
        };
        assert!(matches!(
            apply_job_patch(&template(), &patch),
            Err(PatchError::ContainerNotFound { .. })
        ));
    }

    #[test]
    fn non_job_shape_is_rejected() {
        let not_a_job = json!({ "hello": "world" });
        let patch = JobPatch {
            job_name: "j".into(),
            ..Default::default()
        };
        assert!(matches!(
            apply_job_patch(&not_a_job, &patch),
            Err(PatchError::Shape(_))
        ));
    }

    #[test]
    fn label_only_patch_does_not_require_containers() {
        // A template with no containers array still takes a name/label patch —
        // we only demand the containers path when an image/env patch needs it.
        let bare = json!({
            "metadata": {},
            "spec": { "template": { "metadata": {} } }
        });
        let patch = JobPatch {
            job_name: "bare".into(),
            labels: vec![("k".into(), "v".into())],
            ..Default::default()
        };
        let out = apply_job_patch(&bare, &patch).expect("label-only patch applies");
        assert_eq!(out["metadata"]["name"], json!("bare"));
        assert_eq!(
            out["spec"]["template"]["metadata"]["labels"]["k"],
            json!("v")
        );
    }
}
